---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# ixplorer

<!-- badges: start -->
<!-- badges: end -->

El paquete ixplorer para llevar funcionalidad de ixplorer cerca al cliente. 
## Instalación

Gracias por hacer uso de ixplorer. Para hacer uso del paquete ixplorer es 
necesario contar el paquete *gitear*. Si no lo hemos instalado, con la siguiente instrucción podremos lograrlo:

```r
devtools::install_github("ixpantia/gitear")
devtools::install_github("ixpantia/ixplorer")
```

En caso de no contar con el paquete devtools instalado, lo podemos realizar con:

```
install.packages("devtools")
```

# English

The ixplorer package takes the functionality of ixplorer close to the client.

## Installation 

Thanks for using ixplorer. To completely use the ixplorer package you will also need to install the **gitear** package. If you haven't install it yet, with this instruction you can do it:

```r
devtools::install_github("ixpantia/gitear")
devtools::install_github("ixpantia/ixplorer")
```

In case you do not have the devtools package installed on your computer, you
can do it with:

```r
install.packages("devtools")
```

